services:
  content-acquisition:
    build:
      context: .
      dockerfile: Dockerfile.content-acquisition
      args:
        NEXT_PUBLIC_URL: https://unifiedworkflow.innodata.com
        NEXT_PUBLIC_IA_API_URL: ${NEXT_PUBLIC_IA_API_URL}
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      API_TOKEN: ${API_TOKEN}
      NEXT_PUBLIC_IA_API_URL: ${NEXT_PUBLIC_IA_API_URL}
  qualification:
    build:
      context: ./apps/inventory
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
      PORT: 3002
