version: '3.9'
services:
  content-acquisition:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  qualification:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
