version: '3.8'

services:
  content-acquisition:
    build: 
      context: .
      args:
        NEXT_PUBLIC_IA_API_URL: ${NEXT_PUBLIC_IA_API_URL:-https://unifiedworkflow.innodata.com}
        NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL:-http://localhost:3000}
    ports:
      - "3000:3000"
    env_file:
      - .env.local
